#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Sun Apr 19 14:23:14 BST 2026
enableDebugOptions=false
disableUpdateMessage=false
enableShaders=false
maxShadowRenderDistance=16
shaderPack=TerraFirmaGreg-Shaders-Unbound-3.0.2.zip
