#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Fri Mar 13 17:58:22 GMT 2026
disableUpdateMessage=false
enableShaders=true
maxShadowRenderDistance=16
shaderPack=TerraFirmaGreg-Shaders-Unbound-2.0.5.zip
