#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Sat Apr 25 15:04:04 BST 2026
enableDebugOptions=false
disableUpdateMessage=false
enableShaders=false
maxShadowRenderDistance=16
shaderPack=BSL_v10.1.1.zip
